### ISSUE TITLE
Archiving

### ISSUE THREAD

**Issue by JohnEarnest** [Ahris/piper#1]
Hello!

I'm the author of Octo, and I'm now in the process of gathering an archive of Chip8 homebrew from across the web. Piper is a lovely little game; I was delighted to discover it during my research.

Would you consider contributing your game to the collection I have here?

https://github.com/JohnEarnest/chip8Archive

Thanks for your time!

**Comment by microaeris** [comment]
Hello! 

I'm glad you found our project and thanks for your kind words. Sure, I'll submit Piper to your repo.

Great job with Octo btw! The documentation and in-browser assembler and emulator made it incredibly easy to use.

**Comment by JohnEarnest** [comment]
Great! I will look forward to your pull request. If you happen to know anyone else who has written or is writing new Chip8 programs, please send them my way.

I'm very happy to hear that you had fun with Octo and found it easy to get into. If you feel like giving it a spin again sometime, I've made some dramatic improvements since 2017. :)

**Comment by JohnEarnest** [comment]
Your pull request has been merged. Thanks again!
